name: job-server
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - aztec/job-server
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - job-server
      - setup-job-server
