name: setup-mpc-alerts
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - aztec/setup-mpc-alerts
      - aztec/setup-mpc-common
commands:
  deploy-public:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-alerts
dependencies:
  - setup-mpc-common
