name: setup-mpc-common
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - aztec/setup-mpc-common
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-common
