name: setup-mpc-server
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - aztec/setup-mpc-server
      - 'aztec/setup-mpc-common aztec/setup-tools'
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-server
dependencies:
  - build-image
  - setup-mpc-common
  - setup-tools
