name: setup-mpc-webterm
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - aztec/setup-mpc-webterm
      - 'aztec/setup-mpc-common aztec/setup-mpc-client'
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-webterm
dependencies:
  - setup-mpc-common
  - setup-mpc-client
