FROM aztec/setup-tools-build
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y build-essential wget libgmp3-dev pkg-config libssl-dev libgomp1

WORKDIR /usr/src/setup-tools
COPY --from=0 \
  /usr/src/setup-tools/build/setup \
  /usr/src/setup-tools/build/setup-fast \
  /usr/src/setup-tools/build/seal \
  /usr/src/setup-tools/build/verify \
  /usr/src/setup-tools/build/compute_generator_polynomial \
  /usr/src/setup-tools/build/prep_range_data \
  /usr/src/setup-tools/build/compute_range_polynomial \
  /usr/src/setup-tools/build/print_point \
  /usr/src/setup-tools/build/generate_h \
  ./