name: setup-mpc-map
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - aztec/setup-mpc-map
      - aztec/setup-mpc-common
commands:
  deploy:
    cmd: ../ci-scripts/deploy.sh
    args:
      - setup-mpc-map
dependencies:
  - setup-mpc-common
