version: '3'
services:
  setup-post-process:
    build: .
    image: aztec/setup-post-process
    environment:
      MPC_SERVER_HOST: http://localhost:8081
      JOB_SERVER_HOST: job-server
    volumes:
      - .:/usr/src/setup-post-process
      - ${HOME}/.aws:/root/.aws
    depends_on:
      - job-server
      - redis

  job-server:
    build: ../job-server
    image: aztec/job-server
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis
    ports:
      - '8080:80'
    depends_on:
      - redis

  redis:
    image: redis
