name: build-image
build:
  default:
    cmd: ../ci-scripts/build.sh
    args:
      - aztec/build-image
commands:
  deploy-public:
    cmd: ../ci-scripts/deploy-public.sh
    args:
      - build-image
